site_name: Example MkDocs on Vercel
site_url: https://example-mkdocs-on-vercel.vercel.app
theme:
  name: material
  logo: img/logo.png
  favicon: favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark
  features:
    - content.code.copy # Enable code blocks to be copied
markdown_extensions:
  - tables # Enabled GitHub Flavour Markdown Tables
  - pymdownx.highlight: # Enable code block highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Enable inline code highlighting
  - pymdownx.snippets # Enable snippets, which seem transclusion-ish
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid # Enable Mermaid diagrams from `mermaid` code blocks
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
